#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Sources"})
---
sources:
#@overlay/replace
#@overlay/match by=overlay.subset({"image": "secretgen-controller"})
- image: secretgen-controller
  path: .
  docker:
    build:
      pull: false
      noCache: false
      file: Dockerfile.dev
      buildkit: true
